### PR TITLE
updated README.md to add instructions for using packages

### PR DESCRIPTION
**Pull request by marielajennings**
Added instructions for using packages with WebPPL.

### CODE REVIEW

**Comment by null-a** [comment]
This looks good to me. One question -- could we avoid duplication by linking to similar information that's already in [the docs](http://docs.webppl.org/en/master/packages.html#packages)? (Or is saving users from having to click through to the docs the goal?)

**Comment by marielajennings** [comment]
We used WebPPL to teach a class last semester and the students had a hard time finding this information. We wanted to have it included in the README if possible to make it more visible this time around.

**Comment by null-a** [comment]
> students had a hard time finding this information

It sounds like the documentation isn't as easy to use/navigate as we'd hope. It would be great if we could improve the usability of the docs directly, rather than duplicate information to workaround the problem, but I don't know how to do that. (Suggestions welcome!) Given that, what do you think to the following as an alternative solution -- we could extend the "Quick start" section of the readme to include something like:

<hr/>

Require a WebPPL package:

```
webppl myprogram.wppl --require packageName
```
See the [packages](http://docs.webppl.org/en/master/packages.html#packages) section of the documentation for more information.

<hr/>

The idea is to fix your problem without incurring too much duplication. What do you think?

**Comment by marielajennings** [comment]
That would be great, thank you!

**Comment by null-a** [comment]
@marielajennings Great! Addressed in #909.

**Pull request closed without merging**
