### PR TITLE
Reparameterization trick for Exponential and Cauchy distributions.

### PR DESCRIPTION
**Pull request by null-a**

### CODE REVIEW

**Comment by dritchie** [comment]
Is it a good idea to use `Uniform({a: 0, b: 1})` as the base distribution? When the base values are being optimized, they won't obey the implicit [0,1] bounds. Wouldn't it be better to use a sigmoid somewhere in `transform`, and have `base` be `Gaussian`? Let me know if I'm missing something here.

**Comment by null-a** [comment]
> When the base values are being optimized

I'm not sure what you mean by "base values"? Nothing to do with the base distribution is optimized, and auto-guides still generate the same guide parameters + squishing functions as before.

**Comment by dritchie** [comment]
Ah, right--the base distribution is only ever sampled. I was mixing up my internal warning signals from HMC with the ones from variational ;)

**Comment by null-a** [comment]
CI failure is unrelated to this change. (It was the uniformDrift test, #430.)

**Pull request merged**
