### PR TITLE
sampleWithFactor Fix

### PR DESCRIPTION
**Pull request by null-a**
This fixes `sampleWithFactor` using `cpsForEach` as discussed in #36. I tested it by running `hmmIncremental` and `hmmSampleWithFactor`, the outputs from which are identical.

I'm not currently extending the stack address when calling `extraScoreFn` as my first impression was that it's not necessary. Am I right?

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Neat, thanks!

Since `extraScoreFn` shouldn't make any calls to `sample`, it's not necessary to pass the address.

I wonder if running `cpsForEach` in each sample statement is significantly slower than the previous `for (var s in supp)` procedure. If so, it could be better to leave the previous `sample` implementation unchanged and just move copy over your new implementation to `sampleWithFactor`.

**Comment by null-a** [comment]
Thanks. I did do a quick benchmark to check it wasn't horrendously slow, but I agree it makes sense to do this. Good call!

**Comment by stuhlmueller** [comment]
Thanks for the change!

Two minor comments: 

1. Rename `queueContinuation` to `enqueueContinuation`? I think it's a bit clearer. My first thought was that `queueContinuation` might call a continuation.

2. Could you refer to `env.coroutine` instead of assigning `coroutine = this` and referring to `coroutine`? This shouldn't change anything, and is more in line with how we're accessing the coroutine elsewhere at the moment.

Other than that, looks great!  If you make those changes, feel free to merge the pull request yourself.

**Comment by null-a** [comment]
No problem! Good suggestions - I've made the changes and merged.

**Pull request merged**
