### PR TITLE
Use new Infer interface throughout.

### PR DESCRIPTION
**Pull request by null-a**
As [discussed](https://github.com/probmods/webppl/pull/688#discussion_r85776862) on #688.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Nice! Should we update the docs, too?

**Comment by null-a** [comment]
I updated them to `Infer({method: '...', model: model})`, but I didn't change that to `Infer({method: '...', model})` to avoid confusing folk who aren't aware of the short hand syntax yet. Are you suggesting we change the docs to the latter?

**Comment by stuhlmueller** [comment]
I don't think we should use the shorthand syntax everywhere (for the reason you mention), but maybe we should add a sentence about it somewhere if we're planning to use it in essentially all of our code?

**Comment by null-a** [comment]
I thought the same. The snag is that the sensible place for such seems to be on a page describing the language, which of course we don't have, yet.

**Comment by null-a** [comment]
As a stopgap, we could give the shorthand version underneath the usage example here:
http://webppl.readthedocs.io/en/dev/inference/index.html

**Comment by stuhlmueller** [comment]
OK.

**Pull request merged**
