### PR TITLE
Enforce bounds in Beta sampler

### LINKED ISSUE #513: Beta sampler generates values that are assigned probability 0 by beta scorer
Example:

~~~~
var dist = Beta({ a: 9999, b: .1 });
repeat(10000, function(){
  var y = sample(dist);
  console.log(y, dist.score(y));
});
~~~~

Output:

~~~~
0.9999944251046955 9.500082244066284
0.999999999999993 28.00260614334479
0.9999999999999998 31.10759493466093
0.9999999992384712 17.564423035228614
0.9999999999993433 23.914705291830202
0.9999998382602882 12.74023957046996
0.9999864449267939 8.620657050939231
0.9999680232708192 7.664050353998103
0.9999999936399531 15.654150368827445
0.9999999707001627 14.279129430087254
0.999999999999692 24.596186353300656
1 -Infinity
0.9999969292803744 10.061844538802097
0.9999999997777188 18.672674770645937
0.9999999774924908 14.51655701186215
1 -Infinity
0.9999999987343763 17.107224932221094
0.9999902941007841 8.959765854819514
0.999999998769428 17.13250265905327
0.9999999967691101 16.26373198923544
1 -Infinity
0.9999852757948278 8.534509224540809
0.9999999999902247 21.484353640064146
0.9999999992791242 17.613798501586142
0.9999999995895558 18.120705721200977
0.999984658180676 8.491353550370636
0.9999999999083781 19.470321362369212
0.9999998614556618 12.879789605940116
0.9999983669743229 10.644548298586578
~~~~

This could be addressed in the same way as #401.

### PR DESCRIPTION
**Pull request by stuhlmueller**
Closes #513.

### CODE REVIEW

**Comment by null-a** [comment]
Have you seen [this comment](https://github.com/probmods/webppl/pull/401#issuecomment-219682386)? Thoughts?

**Comment by stuhlmueller** [comment]
Thanks for the pointer! It does make sense to bump both Beta and Dirichlet to the closest number in floating point representation, so I made that change.

**Comment by null-a** [comment]
Looks good to me, but @longouyang is the expert!

**Comment by longouyang** [comment]
Looks good to me!

**Pull request merged**
