### PR TITLE
Make rejuvenation work for the varFactors tests.

### PR DESCRIPTION
**Pull request by null-a**
As discussed in #176.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Do you think we should make the naming of `proposalBoundary` and `exitFactor` more analogous? They seem to fill similar roles in that they control the initial and final bounds of the MH re-evaluation region. Maybe `proposalBoundary` should be `startERPIndex`, and `exitFactor` `exitFactorIndex`? On that note, `exitFactor` is currently 1-indexed, right? I wonder if it should be 0-indexed, with default `-1` to indicate no limit.

Can rejuvenation lead to completed particles reverting to non-complete status? If `exitFactor` is `k` and we switch from a branch with `< k` factors to a branch with `> k` factors, then this should happen, right? (Assuming that this is the only thing going on in the program.)

**Comment by null-a** [comment]
> Do you think we should make the naming of proposalBoundary and exitFactor more analogous? 

At first I thought this sounded like a good idea, but now I'm not so sure. I'm thinking that:

1. It seems we lose valuable information by dropping the work "proposal". Someone looking at the code might ask "what is it that starts at `startERPIndex`?"
2. Without the "proposal" clue, the analogy might suggest to them that since we stop execution of the program at `exitFactorIndex`, then we must start execution at `startERPIndex`. (Which we don't, of course.)

> exitFactor is currently 1-indexed, right?

That's right. On `Trace` I count how many factor statements an execution has encountered which seems pretty natural to me, and `exitFactor` just follows that. I'm happy to pull in a [change](https://github.com/null-a/webppl/commit/60fe1c924512a325f18d9caa0778349fb502c441) which switches this around if you like. (I've held off while we decide about `startERPIndex` etc.)

> Can rejuvenation lead to completed particles reverting to non-complete status?

Yes, that' the idea.

**Comment by stuhlmueller** [comment]
> Without the "proposal" clue, the analogy might suggest to them that since we stop execution of the program at `exitFactorIndex`, then we must start execution at `startERPIndex`.

It seems to me that this is not too far from the truth -- `MHKernel` only ever re-executes code that comes after `startERPIndex`/`proposalBoundary`. If you want to be entirely explicit, you could call it `minProposalERPIndex`.

> I'm happy to pull in a [change](https://github.com/null-a/webppl/commit/60fe1c924512a325f18d9caa0778349fb502c441) which switches this around if you like.

If you end up renaming `proposalBoundary` to `...Index`, switch it; if not, the previous version is better.

**Comment by stuhlmueller** [comment]
Should I merge this as is? (I'm happy to.)

**Comment by null-a** [comment]
> Should I merge this as is? (I'm happy to.)

Sure.

**Pull request merged**
