### PR TITLE
update ad.js dependency

### PR DESCRIPTION
**Pull request by iffsid**
This change reflects commit 4facddf in ad.js that undoes the shadowing
of hard functions by their smoothed versions
   - max and min were replaced originally by their approrimate,
     differentiable-everywhere versions
   - this has now been undone and the smoothed versions moved to `smax`
     and `smin`.

Fixes: #303

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Thanks! Why not update the version of `ad.js` on npm?

**Comment by iffsid** [comment]
It's complicated -- the packages (multiple versions) were built for `master`, but this is the `simple` branch. The `master` branch is under a big overhaul with the adnn-related changes, and I didn't know how to make packages that were branch specific, or switch branches beneath the versioning on npm :-)

**Comment by stuhlmueller** [comment]
Wouldn't it work to just check out the branch, run `npm version patch`, then `npm publish`? If not, we can go with the PR as it is.

**Comment by iffsid** [comment]
I believe that would work, but the branch that the package was built under would switch. I didn't want to do that. If I was a proper software dev, I would have made a `release` branch that served as the base for npm package publishing but I think that's a lost cause... :-)

Anyways, I'll revert to using the npm versioned packages again once the changes that have been in the pipeline for a while now get pushed out.

**Comment by stuhlmueller** [comment]
OK, thanks! I hope to see the new version of ad.js soon — it would be great to support HMC for multivariate distributions! :-)

**Pull request merged**
