### PR TITLE
Updated webppl.org with demos section

### PR DESCRIPTION
**Pull request by dritchie**
Here's my first crack at updating webppl.org. New content includes:

- List of language features
- List of publications using webppl
- List of demos (currently: 2D vines/lightning from NGPM paper, old procedural spaceships demo from SIGGRAPH 2015)
- Jumbotron header points to demos

Addresses (but doesn't yet close?) #691 

Anyone have any changes they'd like to see made before this gets merged in and goes live? I'd like to do that by Tuesday morning, if possible (some Adobe people are coming to Stanford, and it'd be good to have this up and running).

### CODE REVIEW

**Comment by ngoodman** [comment]
neat --how can i preview the new site?

**Comment by dritchie** [comment]
Here's how to preview:

- Check out the `gh-pages-redesign` branch
- From the root directory of the branch, run `python -m SimpleHTTPServer` (the demo makes some AJAX requests, so it needs to be run under a webserver).
- Point your browser to `localhost:8000`

**Comment by ngoodman** [comment]
nice additions! happy to have this go live today....

some suggestions:

*  it looks a bit awkward to have the "features" live in boxes, but nothing else. maybe loose the boxes but have bullets for the features?

* likewise it's not currently clear why some content is two column and other is one (and why these are intermixed)

* in "documentation" we should perhaps now put the actual docs first, and then have dippl / probmods. also we should point to probmods/v2 (which is actually in webppl).

* in publications we can list the various web books and notes that use webppl: probmods/v2, dippl, agentmodels.org, http://gscontras.github.io/ESSLLI-2016/, maybe others eg MH's BDA class?

* it would be good for the how to cite info to be a top level section separate from the publications...

**Comment by dritchie** [comment]
Done. I'll merge this now. Let me know if anything else seems amiss (e.g. @stuhlmueller, did I get the authors right for agentmodels.org?)

**Pull request merged**
