### PR TITLE
Enable caching transforms based on simple AST test.

### PR DESCRIPTION
**Pull request by null-a**
This is an initial attempt at #135. The transforms are enabled for any program which includes the identifier `IncrementalMH`.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Since this transforms the entire program, it would be good to test that the caching transform doesn't break any of the other inference algorithms. We could have a version of the `simple.wppl` test case that includes a `IncrementalMH` query that does (almost) nothing.

**Comment by null-a** [comment]
That's a great suggestion. I'm pretty sure a few such tests would fail at the moment as a few of the inference coroutines don't define an `incrementalize` method. I assume they should all do something like `Coroutine.prototype.incrementalize = env.defaultCoroutine.incrementalize`. I'll add the tests, fix any failures and add a commit to this PR.

Another thought: At present if you run incremental MH without the transforms there's no indication that anything is wrong. (We've had passing tests for incremental MH *without* the transforms since I refactored the inference tests.) I think we could do with a test or runtime error/warning to catch this, I'm just not sure how best to tackle it yet.

**Comment by dritchie** [comment]
"At present if you run incremental MH without the transforms there's no 
indication that anything is wrong."
Just to be clear: the transforms help IncrementalMH be more efficient, 
but they're not actually necessary for it to be a correct inference 
algorithm.

Adding |Coroutine.prototype.incrementalize| to all the inference 
coroutines is what I did in the incremental-mh branch, but it still rubs 
me the wrong way. It feels wrong and non-modular for every coroutine to 
define an extra method just because of a feature that one of them 
happens to have. I don't have a better suggestion at the moment, though.

-- D

**Comment by null-a** [comment]
>  the transforms help IncrementalMH be more efficient, but they're not actually necessary for it to be a correct inference algorithm.

Since the tests were passing that was my assumption, thanks for confirming!

>  It feels wrong and non-modular for every coroutine to define an extra method

I totally agree. In the absence of a straight-forward solution though, I think it's reasonable to live with it temporarily and clean it up as part of #64.

**Pull request merged**
