### PR TITLE
Show most recent position in user code in errors

### LINKED ISSUE #518: Error handling should show most recent position in user code
This is likely a special case of #314 (see discussion there), but i think it might be easier (and seems especially useful to me).

### PR DESCRIPTION
**Pull request by null-a**
This implements #518 for Node. It should also allow us to straight-forwardly implement a similar thing in Chrome.

~~There are a few loose ends to tie up before merging this but I hope it's very close. I wanted to open the PR now because the review may take sometime.~~

There's a short description of what this looks like to use [here](https://github.com/probmods/webppl/issues/314#issuecomment-232131656).

I did a quick test to ensure that the extra work we do to make this happen doesn't slow things down *too* much, and it appears it doesn't. I'll post some numbers below.

To do:
- [x] Optimize generated code
- [x] Test integration with webppl-editor
- [x] Speed up compilation
- [x] Fix known issues

Closes #518. Partially addresses #314. (This change gives us access to something like a full stack trace, we just don't show the full thing when there's an error.)

### CODE REVIEW

**Comment by null-a** [comment]
> I did a quick test to ensure that the extra work we do to make this happen doesn't slow things down too much, and it appears it doesn't. I'll post some numbers below.

I did a quick test using this program:

```js
Infer({method: 'MCMC', samples: 1e6}, function() {
  return flip() + flip();
});
```

I measured the runtime using `--verbose` before and after this PR. The average runtime for 5 runs was 9.0s before and 8.9s after.

However, I noticed that *compilation* takes longer after this change. Up from ~450ms to ~800ms for the program above. I perhaps need to see if there's an easy way to improve that.

**Comment by longouyang** [comment]
I'm testing the editor with this on the [`use-addressy-errors` branch](/probmods/webppl-editor/tree/use-addressy-errors) (see http://web.stanford.edu/~louyang/wp-editor-2016.07.19/demo/ for the demo page)

Things mostly work, except for two things: canceling jobs (try canceling in the MCMC progress bar example) and trampoline resuming (try the dippl cv example).

These both seem related to the runner, which now appears to take two arguments, `wrapped` and `t` -- I can't quite tell how to use these for canceling and resuming.

Also, while using the Chrome debugger to try to understand resuming in the dippl cv example, I found that the compiled code looks quite odd; there are quite long sequences of `_addr.save(_globalCurrentAddress, _currentAddress)`:

```js
(function (_globalCurrentAddress) {
    return function (p) {
        return function (runTrampoline) {
            return function (s, k, a) {
                var t = p(s, k, a);
                runTrampoline(t);
            };
        };
    }(function (globalStore, _k0, _address0) {
        var _currentAddress = _address0;
        _addr.save(_globalCurrentAddress, _currentAddress);
        var _dummy404 = _addr.save(_globalCurrentAddress, _address0);
        _addr.save(_globalCurrentAddress, _currentAddress);
        _addr.save(_globalCurrentAddress, _currentAddress);
        return function () {
            return resetEnv(globalStore, function (globalStore, _dummy402) {
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                var RandomInteger = function RandomInteger(globalStore, _k392, _address5, params) {
                    var _currentAddress = _address5;
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    var _dummy393 = _addr.save(_globalCurrentAddress, _address5);
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    return function () {
                        return _k392(globalStore, util.jsnew(dists.RandomInteger, params));
                    };
                };
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                var randomInteger = function randomInteger(globalStore, _k348, _address25, arg) {
                    var _currentAddress = _address25;
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    var _dummy351 = _addr.save(_globalCurrentAddress, _address25);
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    var _k350 = function (globalStore, params) {
                        _addr.save(_globalCurrentAddress, _currentAddress);
                        return function () {
                            return RandomInteger(globalStore, function (globalStore, _result349) {
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                return function () {
                                    return sample(globalStore, _k348, _address25.concat('_4'), _result349);
                                };
                            }, _address25.concat('_3'), params);
                        };
                    };
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    return function () {
                        return util.isObject(arg) ? _k350(globalStore, arg) : _k350(globalStore, { n: arg });
                    };
                };
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                var MH = function MH(globalStore, _k50, _address126, wpplFn, samples, burn) {
                    var _currentAddress = _address126;
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    var _dummy51 = _addr.save(_globalCurrentAddress, _address126);
                    _addr.save(_globalCurrentAddress, _currentAddress);
                    return function () {
                        return MCMC(globalStore, _k50, _address126.concat('_121'), wpplFn, {
                            samples: samples,
                            burn: burn
                        });
                    };
                };
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                _addr.save(_globalCurrentAddress, _currentAddress);
                return function () {
                    return Draw(globalStore, function (globalStore, targetImage) {
                        _addr.save(_globalCurrentAddress, _currentAddress);
                        return function () {
                            return loadImage(globalStore, function (globalStore, _dummy26) {
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var uniformDraw = function uniformDraw(globalStore, _k24, _address134, xs) {
                                    var _currentAddress = _address134;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy25 = _addr.save(_globalCurrentAddress, _address134);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return randomInteger(globalStore, function (globalStore, i) {
                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                            return function () {
                                                return _k24(globalStore, xs[i]);
                                            };
                                        }, _address134.concat('_133'), xs.length);
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var drawLines = function drawLines(globalStore, _k21, _address135, drawObj, lines) {
                                    var _currentAddress = _address135;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy23 = _addr.save(_globalCurrentAddress, _address135);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var line = lines[0];
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy22 = drawObj.line(line[0], line[1], line[2], line[3], line[4], line[5], line[6]);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return ad.scalar.pneq(lines.length, 1) ? drawLines(globalStore, _k21, _address135.concat('_134'), drawObj, lines.slice(1)) : _k21(globalStore, undefined);
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var randomStrokeWidth = function randomStrokeWidth(globalStore, _k19, _address136) {
                                    var _currentAddress = _address136;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy20 = _addr.save(_globalCurrentAddress, _address136);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var widths = [
                                        2,
                                        4,
                                        8,
                                        16
                                    ];
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return uniformDraw(globalStore, _k19, _address136.concat('_135'), widths);
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var randomOpacity = function randomOpacity(globalStore, _k17, _address137) {
                                    var _currentAddress = _address137;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy18 = _addr.save(_globalCurrentAddress, _address137);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var opacities = [
                                        0,
                                        0.2,
                                        0.5
                                    ];
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return uniformDraw(globalStore, _k17, _address137.concat('_136'), opacities);
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var _getRandomColor = function _getRandomColor(globalStore, _k13, _address138, i) {
                                    var _currentAddress = _address138;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy16 = _addr.save(_globalCurrentAddress, _address138);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return ad.scalar.eq(i, 0) ? _k13(globalStore, '') : function (globalStore, color) {
                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                            return function () {
                                                return uniformDraw(globalStore, function (globalStore, _result14) {
                                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                                    return function () {
                                                        return _getRandomColor(globalStore, function (globalStore, _result15) {
                                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                                            return function () {
                                                                return _k13(globalStore, ad.scalar.add(_result14, _result15));
                                                            };
                                                        }, _address138.concat('_138'), ad.scalar.sub(i, 1));
                                                    };
                                                }, _address138.concat('_137'), '04AF');
                                            };
                                        }(globalStore, '#');
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var randomColor = function randomColor(globalStore, _k10, _address139) {
                                    var _currentAddress = _address139;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy12 = _addr.save(_globalCurrentAddress, _address139);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return _getRandomColor(globalStore, function (globalStore, _result11) {
                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                            return function () {
                                                return _k10(globalStore, ad.scalar.add('#', _result11));
                                            };
                                        }, _address139.concat('_139'), 6);
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var makeLines = function makeLines(globalStore, _k8, _address140, n, lines) {
                                    var _currentAddress = _address140;
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    var _dummy9 = _addr.save(_globalCurrentAddress, _address140);
                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                    return function () {
                                        return randomInteger(globalStore, function (globalStore, x1) {
                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                            return function () {
                                                return randomInteger(globalStore, function (globalStore, y1) {
                                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                                    return function () {
                                                        return randomInteger(globalStore, function (globalStore, x2) {
                                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                                            var y2 = y1;
                                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                                            return function () {
                                                                return randomStrokeWidth(globalStore, function (globalStore, strokeWidth) {
                                                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                                                    return function () {
                                                                        return randomOpacity(globalStore, function (globalStore, opacity) {
                                                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                                                            return function () {
                                                                                return randomColor(globalStore, function (globalStore, color) {
                                                                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                                                                    var newLines = lines.concat([[
                                                                                            x1,
                                                                                            y1,
                                                                                            x2,
                                                                                            y2,
                                                                                            strokeWidth,
                                                                                            opacity,
                                                                                            color
                                                                                        ]]);
                                                                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                                                                    return function () {
                                                                                        return ad.scalar.eq(n, 1) ? _k8(globalStore, newLines) : makeLines(globalStore, _k8, _address140.concat('_146'), ad.scalar.sub(n, 1), newLines);
                                                                                    };
                                                                                }, _address140.concat('_145'));
                                                                            };
                                                                        }, _address140.concat('_144'));
                                                                    };
                                                                }, _address140.concat('_143'));
                                                            };
                                                        }, _address140.concat('_142'), 50);
                                                    };
                                                }, _address140.concat('_141'), 50);
                                            };
                                        }, _address140.concat('_140'), 50);
                                    };
                                };
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                var counter = [];
                                _addr.save(_globalCurrentAddress, _currentAddress);
                                return function () {
                                    return MH(globalStore, _k0, _address0.concat('_151'), function (globalStore, _k1, _address141) {
                                        var _currentAddress = _address141;
                                        _addr.save(_globalCurrentAddress, _currentAddress);
                                        var _dummy7 = _addr.save(_globalCurrentAddress, _address141);
                                        _addr.save(_globalCurrentAddress, _currentAddress);
                                        return function () {
                                            return makeLines(globalStore, function (globalStore, lines) {
                                                _addr.save(_globalCurrentAddress, _currentAddress);
                                                var showOutputImage = ad.scalar.eq(counter.length % 100, 0);
                                                _addr.save(_globalCurrentAddress, _currentAddress);
                                                return function () {
                                                    return Draw(globalStore, function (globalStore, finalGeneratedImage) {
                                                        _addr.save(_globalCurrentAddress, _currentAddress);
                                                        return function () {
                                                            return drawLines(globalStore, function (globalStore, _dummy6) {
                                                                _addr.save(_globalCurrentAddress, _currentAddress);
                                                                var newScore = ad.scalar.div(ad.scalar.sub(0, targetImage.distance(finalGeneratedImage)), 1000);
                                                                _addr.save(_globalCurrentAddress, _currentAddress);
                                                                var _k5 = function (globalStore, _dummy4) {
                                                                    _addr.save(_globalCurrentAddress, _currentAddress);
                                                                    return function () {
                                                                        return factor(globalStore, function (globalStore, _dummy3) {
                                                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                                                            var _dummy2 = counter.push(1);
                                                                            _addr.save(_globalCurrentAddress, _currentAddress);
                                                                            return function () {
                                                                                return _k1(globalStore, lines);
                                                                            };
                                                                        }, _address141.concat('_150'), newScore);
                                                                    };
                                                                };
                                                                _addr.save(_globalCurrentAddress, _currentAddress);
                                                                return function () {
                                                                    return showOutputImage ? _k5(globalStore, undefined) : _k5(globalStore, finalGeneratedImage.destroy());
                                                                };
                                                            }, _address141.concat('_149'), finalGeneratedImage, lines);
                                                        };
                                                    }, _address141.concat('_148'), 50, 50, showOutputImage);
                                                };
                                            }, _address141.concat('_147'), 8, []);
                                        };
                                    }, 2500);
                                };
                            }, _address0.concat('_132'), targetImage, 'beach.png');
                        };
                    }, _address0.concat('_131'), 50, 50, !0);
                };
            }, _address0.concat('_0'));
        };
    });
});
```

**Comment by null-a** [comment]
@longouyang Great, thanks for trying it out.

> Things mostly work except for two things: canceling jobs

I expect this to still work. It looks like you just need to set `comp.runner = runner` as before?

> and trampoline resuming

Ah, right, I missed we were doing that. I've rejigged things to make this possible. I've updated my [browser usage example](https://gist.github.com/null-a/e5952a24cbb74c5d2a4f05e712db3064) accordingly.

> I found that the compiled code looks quite odd

Yeah, I [already knew](https://github.com/null-a/webppl/blob/481c22937f3feca32954294138b199b221c2e70a/src/transforms/stack.js#L56) about that, but thanks for mentioning it! It's now fixed.

**Comment by null-a** [comment]
> However, I noticed that compilation takes longer after this change. Up from ~450ms to ~800ms for the program above. I perhaps need to see if there's an easy way to improve that.

I've resolved this. The fix slightly lowers my confidence that the way I'm tracking the current address will always work out, but I'd guess it's fine.

**Comment by longouyang** [comment]
Update for paper trail: I fixed editor to work with the latest changes in this PR and things work great (demo: http://web.stanford.edu/~louyang/wp-editor-2016.07.20/demo)

**Comment by null-a** [comment]
>  I fixed editor to work with the latest changes in this PR and things work great 

Great stuff, thanks @longouyang.

I've fixed the problems I mentioned in my original comment, this is now good to review. The most recent CI failure was caused by the beta sampler tests, other than that the tests are passing.

**Comment by stuhlmueller** [comment]
I don't think I sufficiently understand this yet to merge it. Maybe Paul and I can chat about it later today, if he isn't busy with other things. If people are happy to merge based on the fact that it looks like it's behaving correctly, I don't have strong objections to that either.

(Specifically, I'm trying to understand how this compares to keeping our system more or less the same, but also extending the address as the first action whenever we enter a function body. Having webppl stack addresses and error positions is great, so I think we'd be okay with paying the price of an extra transform + global variable for that, but I'd like to understand what role they are playing.)

**Comment by longouyang** [comment]
Yes, it'd be useful to know how this is different from extending the address whenever we enter a function body.

**Comment by stuhlmueller** [comment]
Based on my conversation with Paul earlier today, I think we should go ahead and merge this. I still think it's worth considering whether we could replace the additional code transform by instead extending the address when we enter a function body, but it seems that it is not straightforward for at least the following two reasons:

1. Even if we extend the address so that it is correct when an error occurs (which it is not in the current addressing scheme, as described in [this gist](https://gist.github.com/null-a/0d46b3dad63804000c8a02c79d8c16ee)), we still need to be able to access this address in the place where we catch the error. The current PR accomplishes this using a global variable for the current address. Maybe we could achieve it in different ways, but it doesn't seem straightforward (due to trampolining, `setTimeout` in the browser).

2. We would need to make sure that, when we resume from an inference coroutine by calling a continuation and an error happens immediately thereafter, we have the correct address available. There is a worry that this wouldn't happen automatically in the address-extension scheme. (I don't entirely understand this worry; maybe Paul can fill in the details.)

**Comment by longouyang** [comment]
NB: this PR changes how the editor works, so when we pull these changes into master we also need to simultaneously merge the `use-addressy-errors` branch into editor master.

**Pull request merged**
