### PR TITLE
Add sweet.js macros.

### LINKED ISSUE #209: Package wppl files concatenated in differing orders between browser/node
This is problematic when there are dependencies between packages.

The current implementation for the browser is perhaps the most natural as packages are loaded in the order they are specified on the command line, and individual files within a package are loaded in the order they appear in `package.json`.

### PR DESCRIPTION
**Pull request by null-a**
This is a cleaned up version of the macros branch we've been discussing in #153. I don't have any more changes planned so this is ready to be reviewed.

I'm still using an old version of brfs and a patched version of sweet.js in order to get `browserify` working.

Getting brfs updated is more involved than I'd hoped, it's certainly not a trivial bug-fix. I've opened an issue to try and find out whether a PR making the change we need is likely to be accepted, but I've not heard back yet. Perhaps we're best merging this as is so we can see if we're happy with our approach before putting lots of effort into updating brfs and sweet.js?

Perhaps the fork of sweet.js should live under the probmods account?

This also closes #209.

### CODE REVIEW

**Comment by null-a** [comment]
@mhtess Once this change reaches you, you'll need to reverse the order in which the `wppl` files are specified in your `naturalUtils` package. (Something [like this](https://github.com/null-a/real-kinds-priors/commit/ae6c4e7121e31c4b9765a50fb53f41e0969f16a0).) This is because this PR changes the order in which `wppl` files are loaded, and in your package there are dependencies between the `wppl` files.

**Comment by stuhlmueller** [comment]
> Perhaps the fork of sweet.js should live under the probmods account?

Yes, feel free to move it there.

**Comment by null-a** [comment]
> Yes, feel free to move it there.

Thanks. Done!

**Comment by stuhlmueller** [comment]
Looks pretty good overall. A few comments:

- I found it difficult to understand what the type of `extra`/`extras` is. My thinking went something like this:

    1. `webppl.prepareExtras(packages)` takes an array of packages as arguments, so it probably returns an array of extras, whatever those are.
    2. Let's look at what it actually returns. It's an array of ASTs and an array of macros. So I guess an extra is roughly an object `{ ast, macros }`.
    3. Let's check this idea. `parseExtra` takes an `extra` as an argument. Looking at its code, it assumes that the extra is of the form `{ wppl, macros }`, so that's different from what I thought.
    4. Let's look at other places where `extras` is used. In `compile`, `extras` is (the same type as) the return value of `prepareExtras()`, so maybe it's `{ ast, macros }` after all?

- I wonder if we should have a more unified treatment of header and packages. Once we have dependencies between packages (#139), we could have a `core` package that is an implicit dependence for every other package and that contains the code that's currently in `header.wppl` and `headerMacros.sjs`.

- It's confusing that we have `prepare` and `prepareExtras` which do completely different things. Since `prepare` is only used in the analysis (which itself hasn't been used by anyone in a long time), can we move it there?

- Can we move `cachingRequired` to `transforms/caching`?

- In ` src/browser.js`, it looks like the `underscore` import isn't actually used.

**Comment by null-a** [comment]
> I found it difficult to understand what the type of extra/extras is in different places.

You're right. I was using "extra" to refer to at least 2 things which is awful, thanks for pointing it out! I've refactored this and hopefully it's a little clearer now. Even though I've removed the overloaded use of the term "extra" I'm not overly happy with the new names I've introduced. Please let me know if any better names come to mind.

> I wonder if we should have a more unified treatment of header and packages

I realised this too. This PR takes a *small* step in that direction by treating the header and packages more uniformly, but I agree we should go further eventually.

> It's confusing that we have `prepare` and `prepareExtras`

I've renamed `prepareExtras` which removes the confusion.

I had mixed feelings about moving this. I think there's a case for leaving it where it is as it's usually the case that changing one requires changing (or at least thinking about) the other, so having them nearby seems useful. With that in mind I moved it, but refactored `compile` so that `prepare` could be written in terms of it.

> Can we move cachingRequired to transforms/caching?

Done.

> In src/browser.js, it looks like the underscore import isn't actually used.

Good catch!

**Comment by stuhlmueller** [comment]
> Even though I've removed the overloaded use of the term "extra" I'm not overly happy with the new names I've introduced. Please let me know if any better names come to mind.

Thanks for the adjustments, this is definitely an improvement. The key question regarding naming seems to be: what should we call a pair of code and associated macros? I can't think of a clearly better name than `pair` ("unexpanded code", "bundle", and "spec" are some ideas I had). One could try to avoid the concept entirely by rewriting the pipeline so that it operates more directly on `code` and `macros` (e.g., using `parse` instead of `parseAllPairs`), but I don't know how feasible this is. It's probably not worth worrying about too much, since we'll likely refactor some more when we expand the module system.

> With that in mind I moved it, but refactored `compile` so that `prepare` could be written in terms of it.

Great.

In `browser.js`, would it be possible to move `var extra = webppl.parsePackageCode(packages, verbose);` out of the `run` and `compile` functions and to the top-level so that it is only run once? It seems that this would save some computation.

Would it make sense to get rid of `loadMacros` and to directly call `sweet.loadModule` in the `pkg.js` `load` function?

Typo: convinience

**Comment by null-a** [comment]
> In browser.js, would it be possible to move var extra = webppl.parsePackageCode(packages, verbose); out of the run and compile

Well spotted! The only reason I pass the result of `parsePackageCode` to `run` and `compile` (rather than passing the packages directly) is that I intend to make exactly this move. Unfortunately this doesn't work at present. I think the problem is that `compile` is mutating some of its input which leads to the first call to `run` working but subsequent calls to fail because some parts of the pipeline have been applied twice. I'll look more closely at this at some point, I'm not sure it needs to hold this up though.

> Would it make sense to get rid of loadMacros and to directly call sweet.loadModule in the pkg.js load function?

Good idea, but I don't think so.

`pkg.load` reads the package contents from disk and it only happens in node. The analogous stage in the browser might be the browserify plugin which reads the package contents and stuffs them into `browser.js`. `loadMacros` operates on the contents of a file of macros, and its current position allows it to operate uniformly across node and the browser as the two steps I just mentioned have happened by this point. If we pushed `loadMacros` into `pkg.load` we'd have to add an analogous call into `browser.js` which would make things more complicated I think.

**Comment by null-a** [comment]
> I'll look more closely at this at some point

It turns out that the particular problem I was running into was the fact that the `naming` transform does mutate its input:

````
> ast = parse('(function() { f() })')
{ type: 'Program',
  body: [ { type: 'ExpressionStatement', expression: [Object] } ],
  sourceType: 'script' }
> gen(naming(ast))
'(function (_address0) {\n    f(_address0.concat(\'_0\'));\n});'
> gen(naming(ast))
'(function (_address0) {\n    f(_address0.concat(\'_0\'), _address0.concat(\'_0\'));\n});'
> 
````

`naming` is written using `estraverse.replace`. There doesn't appear to be a straight-forward way to make this non-mutating. I guess the other transforms which use this will be similarly problematic.

I tried the obvious thing of cloning the AST (using lodash) but this took longer than the call to `parsePackageContents` which we're trying to avoid.

**Comment by stuhlmueller** [comment]
> `naming` is written using `estraverse.replace`. There doesn't appear to be a straight-forward way to make this non-mutating. I guess the other transforms which use this will be similarly problematic.

Ok, then let's leave it as it is for now. At some point we'll need to revisit this -- the fact that compile mutates some of its arguments is unexpected behavior. I created issue #247.

**Pull request merged**
