### PR TITLE
Specify default params for sampling convenience functions.

### PR DESCRIPTION
**Pull request by null-a**
As discussed in #187.

### CODE REVIEW

**Comment by null-a** [comment]
Some analysis tests are failing because `flip` now generates member expressions which aren't handled by `analyze`.

@stuhlmueller Are you happy for me to comment these tests out for now, or should we update `analyze`?

**Comment by stuhlmueller** [comment]
Yes, comment out these tests for now -- I don't think anyone is using `analyze` at the moment.

**Comment by stuhlmueller** [comment]
It would be good to have a test that checks that (at least one of the) header functions without parameters does the right thing. The implementation relies on `arguments`, which I implemented in a rather fragile way, so it's easy to imagine that the implementation breaks in the future. Now that I think about it, maybe it would be better to implement this by checking whether `theta` etc. are undefined.

**Comment by null-a** [comment]
> Now that I think about it, maybe it would be better to implement this by checking whether theta etc. are undefined.

Done.

Seeing a bare `gaussian()` in a model made me question whether we even want default arguments for `gaussian`. (And to a lesser extent `uniform`.) Is it sufficiently clear what `gaussian()` means? An alternative would be to have something like a new `stdGaussian` function. This isn't any shorter but it might be convenient if you need to pass it to a higher-order function. (Though I don't think that happens often, so that point is perhaps moot.)

Thinking about *that* idea made me realize that `repeat(3, flip)` will always return `[false, true, true]` because `repeat` passes the current iteration to its second argument. I find this surprising.

If you're happy with the PR as it is, then so am I. If we're unsure, I suggest we just set a default for `flip` which I still feel strongly about.

**Comment by iffsid** [comment]
> `repeat` passes the current iteration to its second argument

This was introduced in 2876516d89c7dcc9f61cf28987c7eb56c4591fd8.
`repeat` should repeat the given thunk `n` times. It shouldn't be adapting the function called according to the iteration.
It appears to have been introduced to replicate functionality provided by `mapN`, which handles this correctly. We should revert this.

**Comment by stuhlmueller** [comment]
> If we're unsure, I suggest we just set a default for `flip` which I still feel strongly about.

Let's just do that for now, and also revert `repeat` as Sid says.

**Comment by null-a** [comment]
Superseded by #195.

**Pull request closed without merging**
