### PR TITLE
Replace multiple Enumerate methods with strategy option.

### PR DESCRIPTION
**Pull request by null-a**
As suggested in #419.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Would you be opposed to using full strategy names (`likely-first`, `breadth-first`, `depth-first`) instead of `lfs`/`bfs`/`dfs`? This would make inference operators more interpretable for people who don't read the docs.

**Comment by null-a** [comment]
> Would you be opposed to using full strategy names

Not at all! I'll take care of it.

**Comment by stuhlmueller** [comment]
Thanks! The PR looks good otherwise, so feel free to merge once you've made that change.

By the way, I'm not sure if we should use camelCase or lisp-case for parameter value strings. The former is more consistent with the naming of keys, and with JavaScript conventions in general, but the latter feels more readable. I'd probably go with camelCase, but not without a tinge of sadness in my lispy heart...

**Comment by null-a** [comment]
>  so feel free to merge once you've made that change.

I've already made the change! I noticed the deviation from camelCase but took your lisp-case suggestion literally anyway. 

On a related note, I realised that because of the way I implemented `Infer`, the values for the `method` key have inherited the convention of using initial capitals from our coroutine naming scheme. (e.g. `IncrementalMH`, `Enumerate`.) Perhaps _all_ of these need to follow a single convention? (Separate PR?)

**Comment by ngoodman** [comment]
it's probably a good idea to use a common convention for params structures in Infer. i'm fine with either camel of lispy. separate PR for sure...

**Pull request merged**
